import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { NewEventInput } from '../../src/store/events.js';
import { appendEvents, closeDb, createEmptyProjectionState, getDb, initDb } from '../../src/store/index.js';
import { graphEventHandlers } from '../../src/graph/projectionHandlers.js';
import { workspaceEventHandlers } from '../../src/workspace/projectionHandlers.js';
import { createKnowledgeQueryService } from '../../src/query/service.js';
import { ReadModelUnavailableError, InvalidQueryError } from '../../src/query/errors.js';
import type { EventHandlerRegistry } from '../../src/store/projectionState.js';

const handlers: EventHandlerRegistry = { ...graphEventHandlers, ...workspaceEventHandlers };
const projection = () => createEmptyProjectionState();
let dir: string;
const event = (eventType: NewEventInput['eventType'], payload: unknown, eventVersion = 1): NewEventInput => ({ eventType, eventVersion, runId: 'query-test', batchId: null, actor: 'system', entityId: null, entityType: null, timestamp: new Date().toISOString(), payload });
const family = (id: string) => event('FAMILY_CREATED', { family_id: id, label: id });
const claim = (id: string, familyId: string, text: string, at: string) => event('CLAIM_OBSERVED', { observation: { id: `obs-${id}`, familyId, runId: 'query-test', observedAt: at, subjectText: text, predicate: 'improves', objectText: 'research', polarity: 'asserted', hedge: 'certain', evidenceType: 'study', canonicalKey: { subject: text.toLowerCase(), predicate: 'improves' }, confidence: 0.9, sourceIds: [], extractionVersion: 'v1' }, reconciliation: { observationId: `obs-${id}`, classification: 'new_claim', canonicalClaimId: id, score: 1, method: 'canonical_key_exact', rationale: 'test', reconcilerVersion: 1, candidates: [] } });
const source = (id: string) => event('SOURCE_OBSERVED', { sourceId: id, observedSourceId: id, canonicalUrl: `https://${id}.example.com`, url: `https://${id}.example.com`, title: id, domain: `${id}.example.com`, sourceType: 'web', isPrimary: true, extractionStatus: 'extracted', runId: 'query-test', observedAt: '2024-01-01T00:00:00.000Z' });
function append(...events: NewEventInput[]): void { appendEvents(events, { projection: projection(), handlers }); }
function service() { return createKnowledgeQueryService(getDb()!); }

beforeEach(() => { dir = fs.mkdtempSync(path.join(os.tmpdir(), 'trellis-query-')); expect(initDb(path.join(dir, 'test.db'))).not.toBeNull(); getDb()!.prepare("UPDATE rm_state SET status='ready' WHERE model_name='knowledge'").run(); });
afterEach(() => { closeDb(); fs.rmSync(dir, { recursive: true, force: true }); });

describe('knowledge query service', () => {
  it('gets and parses claims and sources, including absence', () => { append(family('f'), claim('c', 'f', 'claim', '2024-01-01T00:00:00.000Z'), source('s')); const q = service(); expect(q.getClaim('c').data?.id).toBe('c'); expect(q.getSource('s').data?.id).toBe('s'); expect(q.getClaim('missing').data).toBeNull(); expect(q.getSource('missing').data).toBeNull(); });
  it('lists claims in last-seen descending then id ascending order', () => { append(family('f'), claim('b', 'f', 'b', '2024-01-02T00:00:00.000Z'), claim('a', 'f', 'a', '2024-01-02T00:00:00.000Z'), claim('c', 'f', 'c', '2024-01-01T00:00:00.000Z')); expect(service().listClaims().items.map(x => x.id)).toEqual(['a', 'b', 'c']); });
  it('filters claims by family', () => { append(family('one'), family('two'), claim('a', 'one', 'a', '2024-01-01T00:00:00.000Z'), claim('b', 'two', 'b', '2024-01-02T00:00:00.000Z')); expect(service().listClaims({ familyId: 'one' }).items.map(x => x.id)).toEqual(['a']); });
  it('composes claim family and FTS filters', () => { append(family('one'), family('two'), claim('a', 'one', 'uniquealpha', '2024-01-01T00:00:00.000Z'), claim('b', 'two', 'uniquealpha', '2024-01-02T00:00:00.000Z'), claim('c', 'one', 'other', '2024-01-03T00:00:00.000Z')); expect(service().listClaims({ familyId: 'one', q: 'uniquealpha' }).items.map(x => x.id)).toEqual(['a']); });
  it('pages five claims without duplicates or skips', () => { append(family('f'), ...['a','b','c','d','e'].map((id, i) => claim(id, 'f', id, `2024-01-0${i + 1}T00:00:00.000Z`))); const q = service(); const ids: string[] = []; let cursor: string | undefined; let page; do { page = q.listClaims({ limit: 2, cursor }); ids.push(...page.items.map(x => x.id)); cursor = page.nextCursor ?? undefined; } while (cursor); expect(ids).toHaveLength(5); expect(new Set(ids).size).toBe(5); expect(page!.nextCursor).toBeNull(); });
  it('uses id tie-breaker for identical timestamps', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-01T00:00:00.000Z'), claim('b', 'f', 'b', '2024-01-01T00:00:00.000Z'), claim('c', 'f', 'c', '2024-01-01T00:00:00.000Z')); const q = service(); const first = q.listClaims({ limit: 2 }); const second = q.listClaims({ limit: 2, cursor: first.nextCursor! }); expect(first.items.map(x => x.id)).toEqual(['a', 'b']); expect(second.items.map(x => x.id)).toEqual(['c']); });
  it('sorts nullable claim timestamps last and paginates null boundary', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-02T00:00:00.000Z'), claim('b', 'f', 'b', '2024-01-01T00:00:00.000Z')); getDb()!.prepare("UPDATE rm_claims SET last_seen_at = NULL WHERE id = 'b'").run(); const q = service(); const first = q.listClaims({ limit: 1 }); const second = q.listClaims({ limit: 1, cursor: first.nextCursor! }); expect(first.items[0]!.id).toBe('a'); expect(second.items[0]!.id).toBe('b'); expect(second.nextCursor).toBeNull(); });
  it('lists observations scoped by claim and ordered by observed time', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-02T00:00:00.000Z'), claim('b', 'f', 'b', '2024-01-01T00:00:00.000Z')); expect(service().listClaimObservationsForClaim({ claimId: 'a' }).items.map(x => x.id)).toEqual(['obs-a']); });
  it('filters evidence by stance', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-01T00:00:00.000Z'), source('s'), event('EVIDENCE_LINKED', { id: 'e1', claimId: 'a', sourceId: 's', observationId: 'obs-a', stance: 'supports', runId: 'query-test' }, 2), event('EVIDENCE_LINKED', { id: 'e2', claimId: 'a', sourceId: 's', observationId: 'obs-a', stance: 'opposes', runId: 'query-test' }, 2)); expect(service().listEvidenceForClaim({ claimId: 'a', stance: 'supports' }).items.map(x => x.id)).toEqual(['e1']); });
  it('scopes relations by direction', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-01T00:00:00.000Z'), claim('b', 'f', 'b', '2024-01-02T00:00:00.000Z'), claim('c', 'f', 'c', '2024-01-03T00:00:00.000Z'), event('EDGE_ADDED', { id: 'r1', fromClaimId: 'a', toClaimId: 'b', relation: 'supports', strength: 'strong', score: 1, runId: 'query-test' }), event('EDGE_ADDED', { id: 'r2', fromClaimId: 'c', toClaimId: 'a', relation: 'supports', strength: 'strong', score: 1, runId: 'query-test' })); const q = service(); expect(q.listClaimRelations({ claimId: 'a', direction: 'from' }).items.map(x => x.id)).toEqual(['r1']); expect(q.listClaimRelations({ claimId: 'a', direction: 'to' }).items.map(x => x.id)).toEqual(['r2']); expect(q.listClaimRelations({ claimId: 'a' }).items.map(x => x.id)).toEqual(['r1', 'r2']); });
  it('blocks all data methods while dirty but permits status', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-01T00:00:00.000Z'), source('s'), event('EVIDENCE_LINKED', { id: 'e1', claimId: 'a', sourceId: 's', observationId: 'obs-a', stance: 'supports', runId: 'query-test' }, 2), event('EDGE_ADDED', { id: 'r1', fromClaimId: 'a', toClaimId: 'a', relation: 'supports', strength: 'strong', score: 1, runId: 'query-test' })); const q = service(); getDb()!.prepare("UPDATE rm_state SET status='dirty' WHERE model_name='knowledge'").run(); expect(q.status().status).toBe('dirty'); expect(() => q.getClaim('a')).toThrow(ReadModelUnavailableError); expect(() => q.getSource('s')).toThrow(ReadModelUnavailableError); expect(() => q.listClaims()).toThrow(ReadModelUnavailableError); expect(() => q.listSources()).toThrow(ReadModelUnavailableError); expect(() => q.listClaimObservationsForClaim({ claimId: 'a' })).toThrow(ReadModelUnavailableError); expect(() => q.listEvidenceForClaim({ claimId: 'a' })).toThrow(ReadModelUnavailableError); expect(() => q.listClaimRelations({ claimId: 'a' })).toThrow(ReadModelUnavailableError); });
  it('handles special FTS syntax explicitly', () => { append(family('f'), claim('a', 'f', 'a', '2024-01-01T00:00:00.000Z')); try { service().listClaims({ q: '" ^ *' }); } catch (error) { expect(error).toBeInstanceOf(InvalidQueryError); } });
});
